### ISSUE TITLE
Show progress for download content

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#912] opened 2021-08-04 08:26 UTC
## Overview

In Bero, there's currently 3 different moments when users can make content offline:
* Course Lessons
* Learning Activities
* Resources

On a Course, users can select which Lessons to make offline and will see a loading spinner. Learning Activities and Resources have a similar control but no loading information is being displayed which can lead to confusion if the contents are large enough for the process to take more than just a few milliseconds.

## Conditions of satisfaction

- [ ] Animate "make offline" for Learning Activities and Resources.

## Resources

| Courses | Resources | Learning Activities |
| - | - | - |
![Screen Recording 2021-08-04 at 07 34 55 mov](https://user-images.githubusercontent.com/2813677/128133638-b397d918-d8c0-48b5-bdb2-96fbdc1d67f8.gif) | <img width="375" alt="Screenshot 2021-08-04 at 07 31 00" src="https://user-images.githubusercontent.com/2813677/128133643-fa5a3986-9a3e-4526-90e6-97290dd6c7a3.png"> | <img width="375" alt="Screenshot 2021-08-04 at 07 40 45" src="https://user-images.githubusercontent.com/2813677/128134673-e6a94864-537b-4d45-980c-53876c049fc2.png">

**Comment by megganeturner** [comment] 2021-08-04 22:49
Duplicate of https://github.com/catalpainternational/canoe/issues/908 😊

**Comment by pedro16v** [comment] 2021-08-05 07:59
Mine is nicer, has pictures in it! 😆 

I'll let Andy solve the design issue based on this information and feed it back to Peter's issue once it's done. Thanks Meggan!

**Comment by andrewwapling** [comment] 2021-08-06 01:48
Thanks for spinning this one up @pedro16v – please see proposed design solutions for each scenario:

**1. Teaching Activities** 
https://invis.io/52Y02L9YTRF#/454490471_Learning_Activities_-_Category_Listings
Interaction recommendations:
• Make offline label fades off
• CTA element transitions to loader element and smoothly moves down
• Light blue background tint fades in and download icon flashes smoothly in and out from 50% opacity to 100% opacity to reinforce activity
• Circle stroke fills with blue as item loads from 0% to 100%
• Loaders fades off and available offline label fades in

**2. Offline Courses** 
https://invis.io/52Y02L9YTRF#/446572478_Course_Detail_-_Offline_Modal
Interaction recommendations:
• Make offline label fades off
• CTA element transitions to loader element and smoothly moves down
• File size count transition from full file size in grey to file size counter in cool black
• Light blue background tint fades in and kb counter transitions from 0kb to 100%kb in sync with circle stroke filling with blue as item loads from 0% to 100% (download icon flashes smoothly in and out from 50% opacity to 100% opacity during download duration to reinforce activity)
• Loaders fades off and available offline label fades in

**3. Resources**
https://invis.io/52Y02L9YTRF#/429853508_Resources_List
• Make offline label fades off
• CTA element transitions to loader element and smoothly moves down
• Light blue background tint fades in and download icon flashes smoothly in and out from 50% opacity to 100% opacity to reinforce activity
• Circle stroke fills with blue as item loads from 0% to 100%
• Loaders fades off and available offline label fades in

Please note: all the transitions should be very quick and punchy with smooth movement and fade transitions to create a seamless feel.

**Comment by pedro16v** [comment] 2021-08-09 12:44
I'm stealing Meggan's animation [from here](https://github.com/catalpainternational/canoe/pull/934) for our review — @andrewwapling 

https://user-images.githubusercontent.com/12974326/128655413-fcbc1862-e5af-43f7-a296-5c2f4242a459.mov

**Comment by andrewwapling** [comment] 2021-08-10 23:21
Hi @pedro16v @megganeturner this is looking awesome :) Great work as usual! Some small feedback:

• Make Offline label sits too far away from icon
• Download icon doesn't match updated design i.e. blue download icon and circular outline #0070F0
• The downloading state download icon looks dark cool grey as opposed to blue and also looks a bit big and heavy compared with design

Reference design: https://invis.io/3G10398H6MJX

Hope this feedback is helpful and let me know if you have any queries at all.

**Closed** 2021-08-11 02:29 UTC
Labels: Design

**Comment by pedro16v** [comment] 2021-08-11 12:52
Please follow up on #908
