### ISSUE TITLE
Bug: videos no being played on the app

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#721] opened 2021-06-07 05:28 UTC
This is on Kumul Helt Skul **production**

I uploaded 5 new videos on Kumul Helt Skul 
  - 3 are working well and running on the app (Course 7 / Lesson 1 and 2) 
  - 2 are not playing on the app, although they were uploaded and they are listed on Wagtail (Course 5 / Lesson 1 on card 7 and 9)

**Comment by md8n** [comment] 2021-06-07 05:50
Course 5, lesson 1, page 2 - I got the following error message:
```
Access to image at 'https://admin.kumulheltskul.com/media/3_thumb_c8k9wycn.jpg' from origin 'https://kumulheltskul.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by md8n** [comment] 2021-06-07 05:53
Course 5, lesson 1, page 7 - I got the following error message:
```
Access to image at 'https://admin.kumulheltskul.com/media_thumbnails/Screen_Shot_2021-06-04_at_7.29.02_AM.png' from origin 'https://kumulheltskul.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by md8n** [comment] 2021-06-07 06:07
If I directly reference the video for page 7 I can see it downloading (I'll have to wait for an hour to get it).

But the thumbnail is definitely not loading

**Comment by PeteCoward** [comment] 2021-06-07 06:59
Thumbnails issue moved to #722, comments here deleted

**Comment by PeteCoward** [comment] 2021-06-07 07:55
Currently the UI is falling back to the original rendition of the uploaded videos which are mpg files.

**Comment by boerwastaken** [comment] 2021-06-07 08:35
It looks like this has been fixed in the still-open PR:
catalpainternational/canoe-backend#147
of April 16th.

**Comment by PeteCoward** [comment] 2021-06-08 05:22
What has been fixed there? The ffmpeg failure, or the db exception in response to it?
Am reading through the remote transcoding docs you made

**Comment by boerwastaken** [comment] 2021-06-08 06:52
The `fps` thing and some other things.
We don't need to turn on cloud transcoding immediately. If no endpoint is defined, transcodes will be made locally as they were before.

**Comment by boerwastaken** [comment] 2021-06-08 06:54
The DB uniqueness constraint I have trouble reproducing, I need to think about that some more.

**Comment by Juliana-t** [comment] 2021-06-08 07:34
Wicher, I uploaded the videos in mp4 format and they are working on the app
now.

**Comment by boerwastaken** [comment] 2021-06-09 18:00
The DB uniqueness constraint violation is caused by:

> Changed in Django 3.0:
> Model.save() no longer attempts to find a row when saving a new Model instance and a default value for the primary key is provided, and always executes an INSERT.

Of course in the happy-go-lucky style of upgrading this fell by the wayside.

**Comment by boerwastaken** [comment] 2021-06-09 20:22
I haven't gotten to the bottom of the uniqueness constraint violation. That said, catalpainternational/canoe-backend#147 contains a slew of fixes and improvements, and also changes the mutex-ing that is supposed to prevent said constraint violation.

**Closed** 2021-06-10 12:05 UTC
Labels: bug
