### ISSUE TITLE
Course Detail – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#385] opened 2021-02-02 03:24 UTC
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe course detail screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/S910395OHEMF

Please see reference design here: https://invis.io/9FZNZQNBU5H

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by megganeturner** [comment] 2021-02-10 22:54
Hi! Closing this issue as I believe it is a duplicate of https://github.com/catalpainternational/canoe/issues/386, which Kate has completed.

**Closed by megganeturner** 2021-02-10 22:54 UTC
Labels: frontend, visual review

**Comment by andrewwapling** [comment] 2021-02-17 05:05
Hi @megganeturner , I believe this issue is distinct to the Course Detail screen as we have both Course Detail (lessons listing) and Lesson Detail (activity listing) in the MVP release.

In the current state core design system we currently only have the Course Detail which launches straight into the activity card flow with the lessons: https://invis.io/9FZNZQNBU5H

This being said I believe there's some discussion around adding in the Lesson detail screen which will require some design work and discussion to nail down the desired approach.

Just thought we should capture this detail here. Let me know if this doesn't make sense or you require any further clarification.

Thanks again, Andy

**Comment by andrewwapling** [comment] 2021-02-19 00:57
Hi @Juliana-t @megganeturner @katevoss , 

This is the course detail screen design that David made comment on in today's sprint planning session. It would be great to get title, intro, start / continue and the short description accordion integrated in the MVP.

Let me know if you have any queries at all.

Thanks again, Andy
