### ISSUE TITLE
Fix: video thumbnails is not being shown

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#594] opened 2021-04-12 08:20 UTC
Thumbnail of the video is not being displayed.
Tester was using:
IPhone 11 and Safari

Also, a tester with a good bandwidth and connection, reported that the video took a long time to load on both the smartphone and computer

![Screen Shot 2021-04-12 at 5 18 45 PM](https://user-images.githubusercontent.com/52807808/114363258-2f4da100-9bb3-11eb-994c-82d75381d647.png)

**Comment by boerwastaken** [comment] 2021-04-12 09:24
Re thumbnails ("poster" attribute on video element), if they're not explicitly supplied, we have to sit around and wait for the video to be loaded to the extent that its first frame can be decoded.

From the docs:

> poster
>    A URL for an image to be shown while the video is downloading. If this attribute isn't specified, nothing is displayed until the first frame is available, then the first frame is shown as the poster frame.

Currently, we're not supplying this `poster` attribute, since the wagtailmedia Wagtail module doesn't supply it (it's one of those poorly chosen modules that barely does anything for us, and the few things it things it does, it does badly).
[Over here](https://github.com/catalpainternational/canoe-backend/issues/6#issuecomment-728955751) I've proposed to amend that situation.

**Comment by Juliana-t** [comment] 2021-04-14 04:32
From @andrewwapling 

Please see below design direction for the Canoe core illustration fallback to solve this issue:

[Content video fallback](https://invis.io/52Y02L9YTRF#/449627509_Activity_-_Content_-_Video_Fallback
)
The idea being that if no custom thumbnail image is uploaded in the CMS then the above image would show.

Kindly review and let me know your feedback.

Thanks again, Andy

**Comment by Juliana-t** [comment] 2021-04-14 04:33
Also @megganeturner and @andrewwapling can you please let me know what should be the size and format for the video thumbnail image? I would like to add it to our technical guidelines for content managers

**Comment by andrewwapling** [comment] 2021-04-14 04:51
Hi @Juliana-t , The design utilises an image size of 310px x 180px and should appear full width on the card. If possible to allow for auto cropping of user uploaded thumbnail images and/or custom cropping this would be advantageous. 

Hope this helps and let me know if you have any other queries at all.

Thanks again, Andy

**Comment by boerwastaken** [comment] 2021-04-14 13:32
I would again suggest not to rely on user-uploaded thumbnails at all. Even if the user can be bothered to do so, small chance they'd get the dimensions/aspect ratio right. 

Doing the work of checking user-uploaded thumbnail usefulness and providing a UI feedback cycle thereof is about the same level of work (if not more) as auto-extracting a thumbnail and appropriately autoresizing and autoblackbarring it (user-uploaded videos will not all have an aspect ratio of exactly `1.72222222` as needed for the placeholder), where the latter option has the benefit of less friction as no one will be bothered about these thumbnails, and possibility of autoregeneration if something about the desired dimensions or format changes. Adding to that, it's not such a long shot to let the user video-scroll to the video timeline position which they want the thumbnail extracted from if we want to go the extra mile.

**Comment by Juliana-t** [comment] 2021-04-15 00:23
Great, thanks for clarifying Wicher. Lets go to the auto-extracting a
thumbnail from the video. Allowing the user to select the thumbnail from
the video timeline, can be a future unit of work,

**Comment by boerwastaken** [comment] 2021-04-15 09:15
OK, pragmatic!

**Comment by boerwastaken** [comment] 2021-04-15 11:03
@katevoss I can choose to generate a thumbnail with black bars serverside, or I can leave the thumbnail as-is, which is, it'll fit within a specified bounding box (currently 310×180) but it might not completely fill that bounding box (due to different aspect ratio). In the latter case, the frontend will have to make up for it with (I suppose) css margins of color of choice.

The attraction of the latter approach is that pixels painted with CSS don't have to be transferred over the wire (thus, smaller images) and that the margin color can be changed on the fly to our whims (serverside I'd go with black).

so @katevoss is it feasible to do the "blackbarring" on the frontend?

**Comment by katevoss** [comment] 2021-04-15 16:20
@boerwastaken I think this might be a question for @megganeturner who's working on the frontend these days 😃

**Comment by boerwastaken** [comment] 2021-04-15 17:29
Oh thanks for the update @katevoss ! Sorry @megganeturner and hello!
For @megganeturner the question: is it feasible to fit images of guaranteed height (180 px) but moderately variable width (they're video thumbnails, so could be portrait vs landscape, and then 4:3, 16:9, 24:10 and what-have-you - variable, but not to the extreme) into the required 310×180 bounding box, padding left-right or top-bottom as needed?

**Comment by megganeturner** [comment] 2021-04-16 00:50
Hey @boerwastaken I think that should be fine! (:

**Comment by andrewwapling** [comment] 2021-04-19 07:32
Thanks for your support on this @Juliana-t @boerwastaken @megganeturner :)

I whole-heartedly agree that anything we can streamline or automate from a content management perspective is highly desirable i.e. automagically applying a thumbnail from the video. If something goes awry the fall back image can be used. Also desirable is the option to either override the automagically generated poster image with either a chosen keyframe in the video or a custom image for greater design flexibility (perhaps both stretch goals at this stage).

**Comment by PeteCoward** [comment] 2021-04-27 23:40
reviewable on https://jid-staging.temp.build, and https://learn.canoe-redesign.temp.build

**Comment by pedro16v** [comment] 2021-05-07 06:28
Not sure what I'm reviewing here. Should I be able to see an automatically extracted thumbnail already?

Here's what I can see:
* I can see videos and play them
* I can see video controls and a spinning loader
* On `https://canoe-csp.catalpa.build` eventually a frame loaded


JID staging | JID prod | JID prod (after a while) | JID prod (iPhone)
---|---|---|---
![Screenshot 2021-05-07 at 15 11 22](https://user-images.githubusercontent.com/2813677/117406354-e685cf80-af47-11eb-9c0b-f0a07ca2a615.png) | ![Screenshot 2021-05-07 at 15 13 14](https://user-images.githubusercontent.com/2813677/117405688-f7821100-af46-11eb-92e8-eaca299d129e.png) | ![Screenshot 2021-05-07 at 15 18 39](https://user-images.githubusercontent.com/2813677/117406315-dbcb3a80-af47-11eb-9bf0-11d64ed72e89.png) | ![IMG_A685F0679E27-1](https://user-images.githubusercontent.com/2813677/117406891-b2f77500-af48-11eb-8c2b-4e32db1cfdcd.jpeg)

**Comment by pedro16v** [comment] 2021-05-07 06:30
@PeteCoward @Juliana-t  please advise if this solution is what was intended or if I should push this issue back to the to do.

**Comment by boerwastaken** [comment] 2021-05-07 07:09
Thumbnails could not be extracted from all videos on canoe-redesign.
The following videos have thumbnails:

-  Huskey video
-  Olgeta
-  A test video

I've tried creating thumbnails on jid-staging but it's swapping/thrashing like crazy, it needs more memory.

**Comment by PeteCoward** [comment] 2021-06-11 05:42
closing now tracked in #722

**Closed by PeteCoward** 2021-06-11 05:42 UTC
Labels: bug
