### ISSUE TITLE
Teaching topic cards now have full height background image

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#946] opened 2021-08-10 13:47 UTC
## Overview
Based on the UX work that happened [here](https://github.com/catalpainternational/canoe/issues/851), we're changing the teaching topic cards so that the image takes the whole height of the card.

> I can confirm that I've checked the fade approach on the images and that this meets AA accessibility for normal text and AA & AAA for larger text using the top end of the grey in the fade #686868 with white text reversing out. This means any image tone beyond white is only adding to and boosting accessibility well in excess of AAA contrast ratios. This accounts for x4 lines of title text in the current design

— Andy

## Conditions of Satisfaction
- [ ] Card image takes full height
- [ ] Card title is white
- [ ] Card title can take up to 4 lines
- [ ] There's a #686868 fade behind the text, for legibility

## Resources

* Check it on [InVision](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710123_Learning_Activities_-_Categories) 

| Current implementation | The future I | The future II |
| - | - | - |
<img width="375" alt="Screenshot 2021-08-10 at 14 35 41" src="https://user-images.githubusercontent.com/2813677/128878153-a97e5c4a-275a-4497-8c81-169c33e8fc83.png"> | <img width="320" alt="Screenshot 2021-08-10 at 14 36 40" src="https://user-images.githubusercontent.com/2813677/128878133-603515cc-5181-49d1-bd5b-d4fc3577b75d.png"> | <img width="321" alt="Screenshot 2021-08-10 at 14 38 52" src="https://user-images.githubusercontent.com/2813677/128878123-e9425cc0-043a-4ad5-93ce-a40fe65f50f0.png">

**Comment by megganeturner** [comment] 2021-08-11 06:10
Hi @andrewwapling / @pedro16v just checking what these cards should look like with completions?

These are the current implementations:

<img src="https://user-images.githubusercontent.com/12974326/128978281-47f420c8-2d57-4281-ade2-853f28d3b1a8.png" width="250">


<img src="https://user-images.githubusercontent.com/12974326/128978217-e30c1d95-3cc2-4919-9254-c94608495df0.png" width="250">

**Comment by megganeturner** [comment] 2021-08-11 06:26
It's also worth pointing out that images to suit this new card layout will need fit into a very rare space where they are optimised for both landscape & portrait - when you click into topics the header image is better for landscape images

<img src="https://user-images.githubusercontent.com/12974326/128979641-1d4bd9a1-077d-4b17-b107-dccda3ab97a5.png" width="250">

**Comment by pedro16v** [comment] 2021-08-11 06:32
Good question regarding completions. I can't seem to find an example on InVision. I can imagine that it looks the same, hovering over the title area. But let's have @andrewwapling have a got at it.

In regards to your second question, the current situation already demands for careful image picking. Let's see how it works out.

**Comment by megganeturner** [comment] 2021-08-11 07:19
Okay, sounds good!

FYI Andy this is what it looks like now with completions without doing anything - lemme know if you'd like changes or if this is suitable!
<img src="https://user-images.githubusercontent.com/12974326/128986301-40b2ca19-f27c-4e52-9393-5b6a06ea996c.png" width="250">
<img src="https://user-images.githubusercontent.com/12974326/128986311-9db4ae17-aa02-43a3-8c24-f8789dd98d72.png" width="250">

**Comment by pedro16v** [comment] 2021-08-11 09:23
You might need to account for the fact that the title can be up to 4 lines high. Which would mean that the completion circle would be changing position from card to card creating visual awkwardness.

Another question here is that if we should the progress bar for topics (we certainly can, we have the complete/incomplete state of each activity). — @andrewwapling ?

**Comment by andrewwapling** [comment] 2021-08-12 00:05
Hi @megganeturner @pedro16v thanks for flagging this. We've never accounted for any progress bar or completed state check for teaching activity top level categories as the logic of progression isn't applicable here as it is in courses. 

The only place we surface completion is with a check flag on top of image within the teaching activity listing, please see:
https://invis.io/6V102V1VURS9#/443710124_Learning_Activities_-_Listings

**Comment by Juliana-t** [comment] 2021-08-12 08:46
From the product perspective, and as we can consider a teaching activity done once the user marks it as completed, I believe adding feedback on the list of activities to show teachers which ones were completed, would be great. The same for the topics (considering a topic is completed when all teaching activities under that topic are marked as completed. Having said that, it needs to be confirmed with @KaraChesal as well, I am not sure if it is expected that a teacher (or a device) would be doing the same teaching activity more than once – for example, if they are teaching more than 1 class/group of students. Or if for some other reason, it makes no sense to display this feedback to teachers when listing topics and/or activities

**Comment by pedro16v** [comment] 2021-08-20 05:25
Hi @andrewwapling @KaraChesal . Can you catch up on this to decide if we should opt to add back a progress bar to teaching topic cards?

**Closed** 2021-09-01 02:11 UTC
